---
- name: Basic hardening of OS
  hosts: all
  become: true
  tasks:

  - name: Creating manutenção group
    group:
      name: suporte
      state: present

  - name: Adding user Manutenção
    user:
      name: Manutencao
      comment: Administrador
      uid: 1040
      group: suporte

  - name: Setting SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive

  - name: Installing BOTO3
    yum:
      name: {{ packages }}
      state: latest
    vars: 
      packages:
      - boto3
      - phyton
  
  - name: Upgrading all packages
    yum:
      name: '*'
      state: latest

